---
- hosts: all
  gather_facts: false
  tasks:
      - name: Generate vars/main.yml from template on local machine
        local_action:
          module: template
          src: group_vars.j2
          dest: "{{ playbook_dir }}/vars/group_vars.yml"
    #delegate_to: localhost
    #run_once: true

  roles:
    - role: virtio_test
      vars:
        udp: True
        tcp: False
#- role2              #支持加载多个role