---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Import tasks from a specific file within a role
      import_role:
        name: virtio_test
        tasks_from: generate_group_vars
      delegate_to: localhost
      run_once: true

- hosts: all
  gather_facts: false
  roles:
    - role: virtio_test
      vars:
        udp: True
        tcp: False
#- role2              #支持加载多个role