- name: Get Vivado Base Directory
  set_fact:
    base_dir: "{{ exec_bin | dirname }}"
    exec_bin: "{{ exec_bin | basename }}"

- debug:
    msg: "Program Device Result: {{ base_dir }} | {{ exec_bin }}"

- name: Program Device
  register: result
  shell:
    chdir: "{{ base_dir }}"
    cmd: "{{ exec_bin }} -mode tcl -source {{ program_tcl }}"
    warn: false

- debug:
    msg: "Program Device Result: {{ result }}"