- name: Program Device
  register: result
  shell:
    #cmd: {{ vivado_lab }} -mode tcl -source {{ bits_file }}
    cmd: "{{ vivado_lab }}"
    warn: false

- name: Show Program Device Result
  debug:
    msg: "Program Device Result: {{ result }}"