- name: Get Vivado Base Directory
  set_fact:
    base_dir: "{{ exec_bin | dirname }}"
    exec_bin: "{{ exec_bin | basename }}"

- name: Program Device
  register: result
  task:
  - shell:
      cmd: "{{ exec_bin }} -mode tcl -source {{ program_tcl }}"
      warn: false
      chdir: "{{ base_dir }}"
  - debug:
      msg: "Program Device Result: {{ result }}"