- name: Remove all contents from multiple directories
  shell:
    cmd: "[ -d {{ item }} ] && rm -rf {{ item }}/* || mkdir -p {{ item }}"
    warn: false
  loop:
    - "/root/test"
    - "/root/test/tmp"

- name: Copy script files to target
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: '/tmp/script.tar.gz', dest: '/root/test/tmp/script.tar.gz'}

- name: Unarchive tar.gz files
  ansible.builtin.unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    remote_src: yes
  loop:
    - { src: "/root/test/tmp/script.tar.gz",dest: "/root/test/", mode: '0777'}