- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - { path: "/root/script", mode: '0755' }

- name: Copy script files to target
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: '/tmp/script.tar.gz',dest: '/root', mode: '0777'}

- name: Unarchive tar.gz file
  unarchive:
    src: "/root/script.tar.gz"
    dest: "/root/script"
    remote_src: yes