- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - { path: "/root/test/tmp", mode: '0755' }

- name: Copy script files to target
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: '/tmp/script.tar.gz', dest: '/root/test/tmp/script.tar.gz'}

- name: Unarchive tar.gz files
  ansible.builtin.unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    remote_src: yes
  loop:
    - { src: "/root/test/tmp/script.tar.gz",dest: "/root/test/", mode: '0777'}