
- name: Download script
  command: wget -O /tmp/script.tar.gz "http://pan.yusur.tech/?explorer/share/fileDownload&shareID=-AR5INIQ&path=%7BshareItemLink%3A-AR5INIQ%7D%2F&s=9SzPC"
  environment:
    http_proxy: ""
    https_proxy: ""