- name: Get URL headers
  ansible.builtin.uri:
    url: "http://pan.yusur.tech/?explorer/share/fileDownload&shareID=-APoFv5w&path=%7BshareItemLink%3A-APoFv5w%7D%2F&s=y7o1X"
    method: HEAD
  register: web_head

- name: Print Last-Modified header
  ansible.builtin.debug:
    msg: "Last-Modified time is {{ web_head.headers['Last-Modified'] }}"

- name: Download foo.conf
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    use_proxy: no
    mode: '0440'
  environment:
    http_proxy: ""
    https_proxy: ""
  loop:
    - { url: "http://pan.yusur.tech/?explorer/share/fileDownload&shareID=-AR5INIQ&path=%7BshareItemLink%3A-AR5INIQ%7D%2F&s=9SzPC", dest: "/tmp/script.tar.gz" }
    - { url: "http://pan.yusur.tech/?explorer/share/fileDownload&shareID=-APoFv5w&path=%7BshareItemLink%3A-APoFv5w%7D%2F&s=y7o1X", dest: "/tmp/k_machine_2100p_virt_c_civ.bit" }
