---
- name: cpoy tool to target host
  import_tasks: fetch_file.yml
  delegate_to: localhost
  run_once: true

- name: reboot
  block:
    - name: Rebooting the server
      ansible.builtin.reboot:
        msg: "Operating System is about to restart, host:{{ inventory_hostname }}, group:{{ group_names | join(', ') }}"
        reboot_timeout: 600
      when: soc_2100p
  rescue:
    - name: Handle reboot failure
      debug:
        msg: "Restart failed, host: {{ inventory_hostname }}"

- name: cpoy tool to target soc
  import_tasks: copy_file.yml
  when: soc_2100p

- name: cpoy tool to target host
  import_tasks: copy_file.yml
  when: host_2100p
