---
- name: Generate defaults/main.yml from template
  template:
    src: "group_vars.j2"
    dest: "{{ role_path }}/defaults/main.yml"
  delegate_to: localhost
  run_once: true

- name: Cpoy tool to target host
  import_tasks: fetch_file.yml
  delegate_to: localhost
  run_once: true

- name: Debug group_vars
  debug:
    var: soc_2100p
#- name: Rboot System
#  import_tasks: reboot_system.yml
#  vars:
#    host: "{{ soc_2100p or host_2100p }}"
#
#- name: Cpoy tool to target soc
#  import_tasks: copy_file.yml
#  when: soc_2100p
#
#- name: Program device
#  import_tasks: bitstream_loading.yml
#  delegate_to: localhost
#  run_once: true
#
#- name: Trex_udp_test server start
#  import_tasks: start_trex_udp_client.yml
#  when: soc_2100p and udp
#
#- name: Trex_udp_test client start
#  import_tasks: start_trex_udp_client.yml
#  when: soc_2100p and tcp

#- name: cpoy tool to target host
#  import_tasks: copy_file.yml
#  when: host_2100p
