---
- name: Cpoy tool to target host
  import_tasks: fetch_file.yml
  delegate_to: localhost
  run_once: true

- name: Reboot
  block:
    - name: Reboot message
      debug:
        msg: "Operating System is about to restart, host:{{ inventory_hostname }}, group:{{ group_names | join(', ') }}"
      when: soc_2100p
    - name: Rebooting the server
      ansible.builtin.reboot:
        msg: "Operating System is about to restart, host:{{ inventory_hostname }}, group:{{ group_names | join(', ') }}"
        reboot_timeout: 600
      when: soc_2100p
  rescue:
    - name: Handle reboot failure
      debug:
        msg: "Restart failed, host: {{ inventory_hostname }}"
      when: soc_2100p

- name: Rboot System
  import_tasks: reboot_system.yml
  var:
    host: {{ soc_2100p }}

- name: Cpoy tool to target soc
  import_tasks: copy_file.yml
  when: soc_2100p

- name: Program device
  import_tasks: bitstream_loading.yml
  delegate_to: localhost
  run_once: true

- name: Trex_udp_test server start
  import_tasks: start_trex_udp_client.yml
  when: soc_2100p and udp

- name: Trex_udp_test client start
  import_tasks: start_trex_udp_client.yml
  when: soc_2100p and tcp

#- name: cpoy tool to target host
#  import_tasks: copy_file.yml
#  when: host_2100p
