- name: Remove all contents from multiple directories
  shell:
    cmd: " mkdir -p {{ item }} "
    warn: false
  loop:
    - '{{ dst_file | dirname }}'

- name: Copy script files to target
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "{{ src_file }}", dest: '{{ dst_file }}'}

- name: Unarchive tar.gz files
  ansible.builtin.unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    remote_src: yes
  loop:
    - { src: "{{ src_file }}", dest: "{{ dst_file }}", mode: '0777'}
  when: item.src is match(".*(\\.tar\\.gz|\\.tgz)$")
